### ISSUE TITLE
how to combine letscertify with my openresty backend service

### ISSUE THREAD

**Issue by wanghaisheng** [anroots/letscertify#1]
i have implemented several api through openresty,then i want to enable ssl over this  apis,
how could i integrate my backend service container with your letscertify?
how to distribute these certs generated by letscertify to my  client for api access?

**Comment by anroots** [comment]
Hello,

This is a generic cron-like certificate renewal service, which does not particularly concern itself on how the certificates were initially obtained from LetsEncrypt nor which web server is using them. What this service does is automate the renewal of already installed certificates.

It is particularly useful if your web server (or load balancer) is dockerized into a container.

For the initial HTTPS setup, refer to LetsEncrypt and your web server documentation. Exact usage of this is quite implementation specific - refer to the README for Nginx example - but basically, you run this container, then have your web server mount volumes from here and configure it's `.well-known` HTTP path and cert locations.

**Comment by wanghaisheng** [comment]
thx  you mean i should apply a ca  from LetsEncrypt website ,then configure my openresty(ngx lua based nginx) server .well-known HTTP location and cert file location

**Comment by anroots** [comment]
Kindof. Obtain the certificate from Lets Encrypt and configure your web server - again, refer to their documentation on how to do this. Once you have HTTPS set up only _then_ could you benefit from this package as it concerns itself with renewal of the 90-day certificates - not the initial setup process.
